### ISSUE TITLE
Width argument to specify no gap between bars

### ISSUE THREAD

**Issue by nsbatra** [reconhub/incidence2#56] opened 2021-03-20 21:28 UTC
Hello! 
Great improvements on the original package - thank you very much! I really like the ability to facet and to use count data. 

I would like to ask if the plotting functions can allow a width argument or otherwise an option for the there to be no gap between bars. At the US CDC and it seems in Europe as well (see ref below) there is a traditional guideline that epidemic curves (when large enough that cases are not shown as boxes) should be histograms and not bar charts - or at least that there be no spaces between the bars. If this option can be offered I think it would also offer a solution to the varying width and frequency of "white lines"/gaps between bars, which appear for example in the github readme (below).

From the vignette - "white lines"/bar gaps appearing at different frequencies across the plot
![image](https://user-images.githubusercontent.com/52152191/111885540-d79a8c00-899e-11eb-9aad-f218ce6ca5c3.png)

From the vignette - "white lines"/bar gaps of varying thickness across the plot
![image](https://user-images.githubusercontent.com/52152191/111885577-057fd080-899f-11eb-8ea0-4400c4f73442.png)

I tried to include a width argument in plot() but it was not accepted. When I tried to add a geom_col() to plot() and specify width that also did not work. While experimenting, I tried to use geom_col alone directly on a weekly incidence2 object. When I specified width = 7 I was able to achieve non-overlapping bars without any gaps. This makes sense given that it was a weekly incidence object and according to this [ggplot2 issue discussion](https://github.com/tidyverse/ggplot2/issues/2187) which says that geom_col width is interpreted in absolute units (days in this case).

Here is that example - the outbreaks ebola_sim_clean linelist 

```
pacman::p_load(incidence2, tidyverse, outbreaks)
b <- incidence2::incidence(outbreaks::ebola_sim_clean$linelist, date_index = date_of_onset, groups = gender, interval = "week")
plot(b, fill = gender) # weird varying white "gaps" between bars
ggplot(data = b)+geom_col(aes(x = bin_date, y = count, fill = gender), width = 7) # no gaps
```

I just wanted to chime in and see if this was something that is possible. Perhaps at the least the width argument could be allowed to pass to the underlying geom_col? Then the user could tinker and find the correct width?

Thanks very much for considering! 

[ECDC guidelines for presentation of surveillance data](https://ecdc.europa.eu/sites/portal/files/documents/Guidelines%20for%20presentation%20of%20surveillance%20data-final-with-cover-for-we....pdf)

**Comment by tjtnew** [comment] 2021-03-21 20:49
Hello, good suggestion re: the width.

I'm pretty sure the irregularity of the white lines is being caused by the resolution of the saved image.  If you recreate the plot in R and look at it interactively (and on a large screen) you will see the lines are evenly spaced.  I will regenerate the vignettes to fix the issue.

In regards to the width argument, I will add the argument to `plot.incidence2` and probably also to `scale_x_incidence`.  It may be sensible to default to full width (I think ggplot2 defaults to 90%) as this would avoid any issue with resolution.  This should be straightforward for `yrwk`, `yrmon` `yrqtr` but may be a little more fiddly for arbitrary periods.

For info, I've split off the logic for the grouped dates in to a separate package called [**grates**](https://cran.r-project.org/web/packages/grates/).  This package has zero strong dependencies so if you didn't want the overhead of **incidence2** you may like that.  It also fixes some bugs I found in the current master branch of **incidence2** plus has expanded documentation on the class implementations. This week I'll be dropping the current implementation and pulling in grates as a dependency going forward.

We're closing in on the stable 1.0 release it's now just ironing out these little issues like widths etc.  Hopefully within the next week or two assuming nothing urgent comes up.

**Comment by nsbatra** [comment] 2021-03-21 21:09
Thanks for the follow-up Tim, I look forward to the 1.0 release. And for sharing grates - good to know!

I've also realized that my original temporary solution of providing `width = 7` to `geom_col()` won't work for months, as each month has a different number of days. But it sounds like there is more complexity going on in the background with grates etc, so I hope the width 100% solution is straight-forward for you.

Thanks again,

**Comment by tjtnew** [comment] 2021-03-21 21:30
yep - when I integrate **grates** this should all just work by setting `width = 1` as a `yrwk`, `yrqtr` and `yrmon` will always be treated as 1 unit (see below).  Using width = 1 should also work in the current master branch of `incidence2`.  Where it doesn't work is for arbitrary periods of time (created with as_period) but I'm hoping I can hide the additional complexity for this situation from the users.
``` r
library(grates)
library(outbreaks)
library(data.table)
library(tibble)
library(ggplot2)

# load data
dat <- as.data.table(ebola_sim_clean$linelist)

# yearweek
yearweek <- dat[, isoweek := as_yrwk(date_of_onset)
                ][, .(cases_new = .N), keyby = isoweek]
as_tibble(yearweek)
#> # A tibble: 56 x 2
#>    isoweek  cases_new
#>    <yrwk>       <int>
#>  1 2014-W15         1
#>  2 2014-W16         1
#>  3 2014-W17         5
#>  4 2014-W18         4
#>  5 2014-W19        12
#>  6 2014-W20        17
#>  7 2014-W21        15
#>  8 2014-W22        19
#>  9 2014-W23        23
#> 10 2014-W24        21
#> # … with 46 more rows
ggplot(yearweek, aes(isoweek, cases_new)) + geom_col(width=1) + theme_bw() + xlab("")
```

![](https://i.imgur.com/dorH25f.png)

``` r

# yearmonth
yearmonth <- dat[, yrmon := as_yrmon(date_of_onset)
                 ][, .(cases_new = .N), keyby = yrmon]
as_tibble(yearmonth)
#> # A tibble: 13 x 2
#>    yrmon    cases_new
#>    <yrmon>      <int>
#>  1 2014-Apr         7
#>  2 2014-May        67
#>  3 2014-Jun       102
#>  4 2014-Jul       228
#>  5 2014-Aug       540
#>  6 2014-Sep      1144
#>  7 2014-Oct      1199
#>  8 2014-Nov       779
#>  9 2014-Dec       567
#> 10 2015-Jan       427
#> 11 2015-Feb       307
#> 12 2015-Mar       277
#> 13 2015-Apr       185
ggplot(yearmonth, aes(yrmon, cases_new)) + geom_col(width=1) + theme_bw() + xlab("")
```

![](https://i.imgur.com/JRom623.png)

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by nsbatra** [comment] 2021-03-21 22:47
Perfect - thank you!

Perhaps I misunderstood your reply ("Using width = 1 should also work in the current master branch of incidence2."), but I just tried using `width = 1` with the current master branch of **incidence2** and the argument wasn't accepted. Did I do something wrong?

`
# install latest master branch
pacman::p_load_current_gh("reconhub/incidence2@master")

# load data
linelist <- as.data.table(ebola_sim_clean$linelist)

# make incidence
a <- incidence2::incidence(linelist, date_of_onset, interval = "week", groups = gender)

# plot
facet_plot(a)
plot(a, width = 1)  # did not work
`

Error was: `Error in ggplot2::scale_x_continuous(..., trans = yrwk_trans(n = n, firstday = firstday)) : 
  unused argument (width = 1)`

Also, I tried to install **grates** but the repo was an "unknown package". I'm happy till later to try your example above, but I just wanted you to know. Perhaps there are permissions? I used `remotes::install_github("reconhub/grates")` from https://www.reconverse.org/grates/.

**Comment by nsbatra** [comment] 2021-03-21 22:57
Regarding **grates** - I've realized that it's just that "reconhub" should be "reconverse" in the install command in the README.
I got it to install with `remotes::install_github("reconverse/grates")` 

![image](https://user-images.githubusercontent.com/52152191/111923735-efddda00-8a76-11eb-9ce5-b7dc7ed74794.png)

**Comment by tjtnew** [comment] 2021-03-22 22:26
This should hopefully be fixed (as best possible) by https://github.com/reconhub/incidence2/commit/3361373f022899ca5d5e112012422ebf384f3780.  To see the new functionality you will need the master branch of both grates and incidence2.

When the interval is numeric, "x days", "x weeks", "month", "quarter" or "year" and you pass the argument `color=NA` to plot this should now work as desired.  Intervals such as "x months" (where x >= 2) are causing me trouble so I'll raise a separate issue to track this.  Dense plots may still have the white line artefacts but this can hopefully be resolved by users by plotting higher resolution images.

Example:
``` r
library(outbreaks)
library(incidence2)

dat <- ebola_sim_clean$linelist

i_week_sex <- incidence(
  dat,
  interval = "week",
  date_index = date_of_onset,
  groups = gender
)

# no lines
facet_plot(i_week_sex, n_breaks = 3, color = NA)
```

![](https://i.imgur.com/b1lMeXN.png)

``` r
# with lines
facet_plot(i_week_sex, n_breaks = 3)
```

![](https://i.imgur.com/y3IlUhh.png)

Is this the sort of behaviour you were after?

**Comment by nsbatra** [comment] 2021-03-23 14:26
Brilliant, yes this is perfect. Thank you Tim.
I don't think I had the grates masterbranch.

**Closed** 2021-03-29 13:32 UTC
